# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-06 09:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Имя')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(max_length=11, verbose_name='Телефон')),
                ('topic', models.CharField(max_length=30, verbose_name='Тема')),
                ('text', models.TextField(verbose_name='Жалоба')),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2017, 1, 6, 13, 22, 18, 596314))),
            ],
            options={
                'verbose_name_plural': 'Жалобы',
            },
        ),
        migrations.CreateModel(
            name='offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Имя')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(max_length=11, verbose_name='Телефон')),
                ('topic', models.CharField(max_length=30, verbose_name='Тема')),
                ('text', models.TextField(verbose_name='Предложение')),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2017, 1, 6, 13, 22, 18, 594314))),
            ],
            options={
                'verbose_name_plural': 'Предложения',
            },
        ),
    ]
