# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-09 07:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer_and_com', '0003_auto_20170108_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 9, 11, 54, 21, 265185)),
        ),
        migrations.AlterField(
            model_name='offer',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 9, 11, 54, 21, 264185)),
        ),
    ]
