# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2019-07-21 06:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer_and_com', '0004_auto_20170109_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 21, 6, 48, 44, 716046)),
        ),
        migrations.AlterField(
            model_name='offer',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 21, 6, 48, 44, 714864)),
        ),
    ]
