# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-06 09:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lyceum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lyceum_news',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 6, 13, 22, 32, 176091), verbose_name='Дата и время публикации'),
        ),
    ]
