# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-08 19:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lyceum', '0002_auto_20170106_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lyceum_news',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 8, 23, 29, 50, 429462), verbose_name='Дата и время публикации'),
        ),
    ]
