# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-09 07:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lyceum', '0003_auto_20170108_2329'),
    ]

    operations = [
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=60)),
                ('topic', models.CharField(max_length=40)),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Сообщения',
                'db_table': 'messages',
            },
        ),
        migrations.AlterField(
            model_name='lyceum_news',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 9, 11, 54, 21, 220182), verbose_name='Дата и время публикации'),
        ),
    ]
