# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-06 09:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lyceum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='codifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='codifiers')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lyceum.subject', verbose_name='Предмет')),
            ],
            options={
                'verbose_name_plural': 'Кодификаторы',
            },
        ),
        migrations.CreateModel(
            name='dis_learning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='dis_learning')),
                ('year', models.DateField(blank=True, default=datetime.datetime(2017, 1, 6, 13, 22, 18, 582313), null=True, verbose_name='Год')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lyceum.subject', verbose_name='Предмет')),
            ],
            options={
                'verbose_name_plural': 'Дистанционное обучение',
            },
        ),
        migrations.CreateModel(
            name='other',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='other')),
            ],
            options={
                'verbose_name_plural': 'Другие',
            },
        ),
        migrations.CreateModel(
            name='result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='results')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lyceum.subject', verbose_name='Предмет')),
            ],
            options={
                'verbose_name_plural': 'Результаты тестирования',
            },
        ),
        migrations.CreateModel(
            name='training_file',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='training')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lyceum.subject', verbose_name='Предмет')),
            ],
            options={
                'verbose_name_plural': 'Тренировочные задания',
            },
        ),
    ]
