# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-06 09:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files_in_com', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dis_learning',
            name='year',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 1, 6, 13, 22, 32, 183091), null=True, verbose_name='Год'),
        ),
    ]
