# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-08 19:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files_in_com', '0002_auto_20170106_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dis_learning',
            name='year',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 1, 8, 23, 29, 50, 429462), null=True, verbose_name='Год'),
        ),
    ]
