# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-09 07:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files_in_com', '0003_auto_20170108_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dis_learning',
            name='year',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 1, 9, 11, 54, 21, 250184), null=True, verbose_name='Год'),
        ),
    ]
